Adding temporary ping command for role reminder
EPITECH-2022/TwentyTwo pull request #2
Opened 2018-08-30 09:19 UTC by jess-sys

2018-08-30 10:19 UTC, Tina-otoge requested changes
Please refactor conditionals and use Discord.Embed

2018-08-30 10:19 UTC, Tina-otoge commented on cogs/Admin.py
> +                if mrole.name in graduation_roles or mrole.name in self.bot.rank_whitelist:
Use more pythonic way to check if two arrays match instead of using (ugly) nested conditionals

2018-08-30 10:19 UTC, Tina-otoge commented on cogs/Admin.py
> +                    await self.bot.send_message(member, "**EPITECH 2022 Server - Announcement**\n\nDon't forget to ask for city and graduation role in EPITECH 2022 Server.\nYou have to ask them befor
Use Discord.Embed, you can look for examples in the Info cog

2018-08-30 12:29 UTC, jess-sys reviewed
Did the needed improvements.

2018-08-31 11:57 UTC, Tina-otoge approved these changes
Please stop using variables that live for literally 2 lines

2018-08-31 11:58 UTC, merged